INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Muy Bajo','#2196f3','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Bajo','#76ff03','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Medio','#ffeb3b','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Alto','#ff9800','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Muy Alto','#f44336','');