INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Muy Bajo','#2196f3','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Bajo','#76ff03','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Medio','#ffeb3b','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Alto','#ff9800','');
INSERT INTO RIESGO_ESCALA (ESCALA, COLOR, ACCION) VALUES ('Muy Alto','#f44336','');

INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (1, 'Impacto1', 1, 'Afectacion_impacto1');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (2, 'Impacto2', 2, 'Afectacion_impacto2');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (3, 'Impacto3', 3, 'Afectacion_impacto3');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (4, 'Impacto4', 4, 'Afectacion_impacto4');

INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (1, 'Probabilidad1', 1, 'Posibilidad_anual1');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (2, 'Probabilidad2', 2, 'Posibilidad_anual2');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (3, 'Probabilidad3', 3, 'Posibilidad_anual3');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (4, 'Probabilidad4', 4, 'Posibilidad_anual4');
