INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (1, 'Impacto1', 1, 'Afectacion_impacto1');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (2, 'Impacto2', 2, 'Afectacion_impacto2');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (3, 'Impacto3', 3, 'Afectacion_impacto3');
INSERT INTO IMPACTO (ID, ESCALA, NIVEL, AFECTACION_ECONOMICA) VALUES (4, 'Impacto4', 4, 'Afectacion_impacto4');
