INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (1, 'Probabilidad1', 1, 'Posibilidad_anual1');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (2, 'Probabilidad2', 2, 'Posibilidad_anual2');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (3, 'Probabilidad3', 3, 'Posibilidad_anual3');
INSERT INTO PROBABILIDAD (ID, ESCALA, NIVEL, POSIBILIDAD_ANUAL) VALUES (4, 'Probabilidad4', 4, 'Posibilidad_anual4');
